name: Compile Windows CUDA with TensorRT Portable Distribution
on:
  workflow_dispatch:
    inputs:
      release:
        description: Upload to a tagged release?
        required: true
        type: boolean
      dwpose:
        description: Build DWPose?
        required: true
        type: boolean
jobs:
  compile-windows-tensorrt:
    uses: Catflower75/app.enfugue.ai.github/workflows/compile.yml@main
    with:
      os: windows-latest
      api: tensorrt
      release: ${{ inputs.release }}
      dwpose: ${{ inputs.dwpose }}
